services:
    app.controller.item_controller:
        class: App\Controller\ItemController
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@app.repository.item_repository'
            - '@app.service.token_to_user_resolver'
            - '@app.service.item_factory'
            - '@app.service.decrypting_item_serializer'
            - '@app.service.item_updater'
        public: true

    app.controller.security_controller:
        class: App\Controller\SecurityController
        arguments:
            - '@app.service.token_to_user_resolver'
        public: true
