security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            logout:
                path: app.logout
            json_login:
                check_path: /login

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    access_control:
        - { path: '^/item', roles: ROLE_USER }
