version: "3"
services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - 127.0.0.1:${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Use a non-root user
            MYSQL_DB_NAME: ${MYSQL_DB_NAME}
        container_name: securestorage_mysql

    mysql_test:
        image: mysql:5.7
        volumes:
            - ./docker/mysql/data_test:/var/lib/mysql
        ports:
            - 127.0.0.1:${MYSQL_PORT_TEST}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Use a non-root user
            MYSQL_DB_NAME: ${MYSQL_DB_NAME}
        container_name: securestorage_mysql_test

    php:
        build: docker/php
        volumes:
            - .:/app:cached
        working_dir: /app
        container_name: securestorage_php
        depends_on:
            -   mysql

    nginx:
        image: nginx:1.19.0
        ports:
            - 127.0.0.1:${NGINX_PORT}:80
        volumes:
            - .:/app:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
        container_name: securestorage_nginx
        depends_on:
            -   php
