parameters:
    app.encryption_key_path: '%kernel.project_dir%/config/keys/encryption.key'

imports:
    - { resource: services/ }

services:
    _defaults:
        autowire: false
        autoconfigure: false
